LocalAddress = "0.0.0.0"  #内网地址，可以填写127.0.0.1，
WebPort = "8080"    #本机服务端口，可以通过访问http://LocalAddress:WebPort/，来判断转账程序是否成功启动


#日志配置
LogmaxAge = 365       #日志最大保存时间（天）
LogrotationTime = 24  #日志切割时间间隔（小时）
LogPath="./log"
LogFileName="corey"

#mysql配置
MysqlStr="root:xing*2019@tcp(127.0.0.1:3306)/alf?charset=utf8&parseTime=true&loc=Local"
DBLog=1
DatabaseName="databaseName"
#redis配置
RedisAddr=""
RedisPwd=""
RedisKey=""
